import { TBook, TBookCategory, TLibraryBook } from "@/types/book";
import {
  Award,
  BookOpen,
  Crown,
  Globe,
  Headphones,
  Heart,
  Languages,
  Lightbulb,
  Moon,
  Play,
  Shield,
  Star,
  TrendingUp,
} from "lucide-react";

export const books: TBook[] = [
  {
    id: 1,
    title: "Tafsir Ibn Kathir",
    author: "Ibn Kathir",
    description:
      "A comprehensive commentary on the Quran, providing detailed explanations and interpretations of verses.",
    category: "tafsir",
    language: "english",
    pages: 3200,
    rating: 4.9,
    downloads: 15420,
    coverImage:
      "https://images.unsplash.com/photo-1544716278-e513176f20a5?w=300&h=400&fit=crop&crop=center",
    isPremium: false,
  },
  {
    id: 2,
    title: "Sahih Al-Bukhari",
    author: "Imam Al-Bukhari",
    description:
      "The most authentic collection of Hadith literature, essential for understanding Islamic teachings.",
    category: "hadith",
    language: "arabic",
    pages: 2400,
    rating: 5.0,
    downloads: 23150,
    coverImage:
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=400&fit=crop&crop=center",
    isPremium: true,
  },
  {
    id: 3,
    title: "The Noble Quran Translation",
    author: "Muhammad Muhsin Khan",
    description:
      "Clear and accurate English translation of the Holy Quran with detailed footnotes.",
    category: "translation",
    language: "english",
    pages: 850,
    rating: 4.8,
    downloads: 45200,
    coverImage:
      "https://images.unsplash.com/photo-1609220136736-443140cffec6?w=300&h=400&fit=crop&crop=center",
    isPremium: false,
  },
  {
    id: 4,
    title: "Fiqh As-Sunnah",
    author: "Sayyid Sabiq",
    description:
      "Comprehensive guide to Islamic jurisprudence based on Quran and Sunnah.",
    category: "fiqh",
    language: "english",
    pages: 1200,
    rating: 4.7,
    downloads: 8900,
    coverImage:
      "https://images.unsplash.com/photo-1585779034823-7e9ac8faec70?w=300&h=400&fit=crop&crop=center",
    isPremium: false,
  },
  {
    id: 5,
    title: "Riyad As-Salihin",
    author: "Imam An-Nawawi",
    description:
      "Gardens of the Righteous - a collection of authentic Hadiths on various aspects of Islamic life.",
    category: "hadith",
    language: "arabic",
    pages: 680,
    rating: 4.9,
    downloads: 12300,
    coverImage:
      "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=400&fit=crop&crop=center",
    isPremium: false,
  },
  {
    id: 6,
    title: "Stories of the Prophets",
    author: "Ibn Kathir",
    description:
      "Detailed accounts of the lives and teachings of the Prophets mentioned in the Quran.",
    category: "biography",
    language: "english",
    pages: 920,
    rating: 4.6,
    downloads: 18700,
    coverImage:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=400&fit=crop&crop=center",
    isPremium: true,
  },
];

export const FEATURED_BOOKS: TLibraryBook[] = [
  {
    id: 1,
    title: "Tafseer Ibn Kathir - Complete",
    author: "Imam Ibn Kathir",
    category: "Quran & Tafseer",
    format: "PDF",
    pages: 4628,
    downloads: 15420,
    rating: 4.9,
    reviews: 1234,
    language: "Arabic/English",
    publishYear: "Classical",
    description:
      "Complete commentary on the Holy Quran by the renowned Islamic scholar Ibn Kathir. Includes detailed explanations of verses with historical context.",
    cover: "tafseer-cover",
    badge: "Classical Text",
    badgeColor: "from-emerald-500 to-teal-600",
    fileSize: "45 MB",
    difficulty: "Advanced",
    readTime: "200+ hours",
  },
  {
    id: 2,
    title: "Sahih Al-Bukhari Collection",
    author: "Imam Al-Bukhari",
    category: "Hadith Collections",
    format: "Interactive",
    pages: 3200,
    downloads: 12340,
    rating: 4.9,
    reviews: 987,
    language: "Arabic/English/Urdu",
    publishYear: "Classical",
    description:
      "The most authentic collection of Hadith with searchable interface and detailed chain of narration analysis.",
    cover: "bukhari-cover",
    badge: "Most Authentic",
    badgeColor: "from-amber-500 to-orange-600",
    fileSize: "38 MB",
    difficulty: "Intermediate",
    readTime: "150+ hours",
  },
  {
    id: 3,
    title: "The Sealed Nectar (Ar-Raheeq Al-Makhtum)",
    author: "Safiur Rahman Mubarakpuri",
    category: "Biography & Seerah",
    format: "PDF",
    pages: 635,
    downloads: 28950,
    rating: 4.8,
    reviews: 2156,
    language: "English",
    publishYear: "1979",
    description:
      "Award-winning biography of Prophet Muhammad (PBUH) that won first prize in a worldwide competition on the Prophet's biography.",
    cover: "sealed-nectar",
    badge: "Award Winner",
    badgeColor: "from-purple-500 to-violet-600",
    fileSize: "12 MB",
    difficulty: "Beginner",
    readTime: "25 hours",
  },
  {
    id: 4,
    title: "Arabic Grammar for Beginners",
    author: "Dr. Abdur Rahman",
    category: "Arabic Language",
    format: "Interactive",
    pages: 420,
    downloads: 8760,
    rating: 4.7,
    reviews: 543,
    language: "English/Arabic",
    publishYear: "2020",
    description:
      "Modern approach to learning Arabic grammar with interactive exercises and pronunciation guides.",
    cover: "arabic-grammar",
    badge: "Interactive",
    badgeColor: "from-blue-500 to-indigo-600",
    fileSize: "25 MB",
    difficulty: "Beginner",
    readTime: "40 hours",
  },
  {
    id: 5,
    title: "Fortress of the Muslim (Hisn al-Muslim)",
    author: "Sa'id ibn Ali ibn Wahf Al-Qahtani",
    category: "Spirituality & Ethics",
    format: "Audio Book",
    pages: 245,
    downloads: 19870,
    rating: 4.9,
    reviews: 1678,
    language: "Arabic/English",
    publishYear: "1988",
    description:
      "Collection of authentic supplications and dhikr from the Quran and Sunnah for daily spiritual practice.",
    cover: "fortress-muslim",
    badge: "Daily Practice",
    badgeColor: "from-green-500 to-emerald-600",
    fileSize: "15 MB",
    difficulty: "Beginner",
    readTime: "8 hours",
  },
  {
    id: 6,
    title: "Islamic Finance Fundamentals",
    author: "Dr. Omar Al-Muamalat",
    category: "Islamic Finance",
    format: "PDF",
    pages: 380,
    downloads: 4560,
    rating: 4.6,
    reviews: 298,
    language: "English",
    publishYear: "2023",
    description:
      "Comprehensive guide to Islamic banking, finance, and investment principles in the modern world.",
    cover: "islamic-finance",
    badge: "Modern",
    badgeColor: "from-cyan-500 to-blue-600",
    fileSize: "18 MB",
    difficulty: "Intermediate",
    readTime: "30 hours",
  },
];

export const RECENTLY_ADDED = [
  {
    title: "Principles of Islamic Jurisprudence",
    author: "Dr. Mohammad Hashim Kamali",
    category: "Fiqh",
    date: "3 days ago",
  },
  {
    title: "Women in Islam",
    author: "Dr. Jamal Badawi",
    category: "Contemporary Issues",
    date: "1 week ago",
  },
  {
    title: "The Prophet's Prayer Described",
    author: "Shaykh Al-Albani",
    category: "Spirituality",
    date: "2 weeks ago",
  },
];

export const CATEGORIES: TBookCategory[] = [
  { name: "All", count: 324, icon: BookOpen },
  { name: "Quran & Tafseer", count: 45, icon: Crown },
  { name: "Hadith Collections", count: 38, icon: Shield },
  { name: "Islamic History", count: 42, icon: Globe },
  { name: "Arabic Language", count: 36, icon: Languages },
  { name: "Fiqh & Jurisprudence", count: 29, icon: Award },
  { name: "Spirituality & Ethics", count: 31, icon: Heart },
  { name: "Biography & Seerah", count: 28, icon: Star },
  { name: "Islamic Finance", count: 18, icon: TrendingUp },
  { name: "Contemporary Issues", count: 22, icon: Lightbulb },
  { name: "Children's Books", count: 35, icon: Moon },
];

export const FORMATS = ["All", "PDF", "Audio Book", "Interactive", "Video"];

export const LIBRARY_STATS = [
  { number: "324+", label: "Islamic Books", icon: BookOpen },
  { number: "150+", label: "Audio Books", icon: Headphones },
  { number: "50+", label: "Interactive Texts", icon: Play },
  { number: "25+", label: "Languages", icon: Languages },
];
