export enum tagTypes {
  admin = "admin",
  user = "user",
  quran = "quran",
  surah = "surah",
  para = "para",
  ayah = "ayah",
  dictionary = "dictionary",
  auth = "auth",
  permission = "permission",
  category = "category",
  book = "book",
  bookContent = "bookContent",
  blog = "blog",
  dua = "dua",
  tafsir = "tafsir",
  bookmark = "bookmark",
}

export const tagTypesList = [
  tagTypes.admin,
  tagTypes.user,
  tagTypes.quran,
  tagTypes.surah,
  tagTypes.para,
  tagTypes.ayah,
  tagTypes.dictionary,
  tagTypes.auth,
  tagTypes.permission,
  tagTypes.category,
  tagTypes.book,
  tagTypes.bookContent,
  tagTypes.blog,
  tagTypes.dua,
  tagTypes.tafsir,
  tagTypes.bookmark,
];
